ARG version=2021.7.1-debian-11-r6
FROM bitnami/scikit-learn-intel:$version

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace
COPY oneapi_cloud oneapi_cloud

# install project deps
RUN pip3 -r ./ai_cloud/requirements.txt

# run inference
ENTRYPOINT ["python", "/workspace/oneapi_cloud/oneapi_cloud/main.py", "disk", "train"]

