apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-loanDefault-app
  namespace: loanDefault-app
  labels:
    app: loanDefault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loanDefault
  template:
    metadata:
      labels:
        app: loanDefault
    spec:
     containers:
       - name: model-image
         image: 
         ports:
           - containerPort: 80
         imagePullPolicy: Always
